=== nirokay/HzgShowAroundData/templates/.schemas/locations.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Locations Array",
    "type": "array",
    "items": {
        "properties": {
            "name": {
                "type": "string",
                "description": "Location name"
            },
            "alias": {
                "type": "array",
                "description": "Location name aliases (used for newsfeed substring replacement)",
                "items": {
                    "type": "string"
                }
            },
            "link": {
                "type": "string",
                "description": "URL to an external resource"
            },
            "desc": {
                "type": "object",
                "description": "Description of a location",
                "patternProperties": {
                    "^": {
                        "type": "array",
                        "description": "Header with paragraphs",
                        "items": {
                            "description": "Paragraph",
                            "type": "string"
                        }
                    }
                }
            },
            "open": {
                "type": "object",
                "description": "(Optionally Multiple) Opening/closing times of the location",
                "additionalProperties": {
                    "type": "object",
                    "description": "Opening times object",
                    "additionalProperties": {
                        "type": "string",
                        "description": "Opening times list item"
                    }
                }
            },
            "pics": {
                "type": "object",
                "description": "Pictures",
                "properties": {
                    "header": {
                        "type": "string",
                        "description": "Header image"
                    },
                    "footer": {
                        "type": "array",
                        "description": "Footer images",
                        "items": {
                            "type": "string",
                            "description": "Footer image"
                        }
                    }
                }
            },
            "same": {
                "type": "array",
                "description": "Collection of names of similar locations",
                "items": {
                    "type": "string"
                }
            },
            "coords": {
                "type": "array",
                "description": "Coords for a rectangle",
                "items": {
                    "type": "integer",
                    "minLength": 4,
                    "maxLength": 4
                }
            },
            "contact": {
                "type": "object",
                "description": "Contact information",
                "properties": {
                    "address": {
                        "type": "string",
                        "description": "Physical address"
                    },
                    "emails": {
                        "type": "object",
                        "description": "Email addresses",
                        "additionalProperties": {
                            "type": "string",
                            "description": "Email address list item"
                        }
                    },
                    "tels": {
                        "type": "object",
                        "description": "Telephone numbers",
                        "additionalProperties": {
                            "type": "string",
                            "description": "Telephone number list item"
                        }
                    }
                }
            }
        },
        "required": ["name"]
    }
}

=== nirokay/HzgShowAroundData/templates/locations.template.json
[
    {
        "name": "",
        "alias": [""],
        "link": "",
        "desc": {},
        "open": {},
        "pics": {},
        "same": [],
        "coords": []
    },
    {
        "name": "",
        "alias": [""],
        "link": "",
        "desc": {},
        "open": {},
        "pics": {},
        "same": [],
        "coords": []
    }
]
